import type { Metadata } from 'next'
import { headers } from 'next/headers'
import Narvbar from '../components/Narvbar'

import { cookieToInitialState } from 'wagmi'

import { config } from './config'
import Web3ModalProvider from '../context'
import { Inter } from "next/font/google";
import "./globals.css";
import React from 'react'


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(config, headers().get('cookie'))
  return (
    <html lang="en">
      <body className={inter.className}><Web3ModalProvider initialState={initialState}>
        <Narvbar/>
        {children}</Web3ModalProvider></body>
    </html>
  );
}
